language: node_js

node_js:
  - "6"

matrix:
  fast_finish: true

cache:
  directories:
    - node_modules

before_script:
  - echo 'America/New_York' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
  - npm install -g grunt-cli
